# Generated by Django 4.1.7 on 2024-05-06 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_alter_children_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='children',
            name='mobile_number',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='children',
            name='name',
            field=models.TextField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='children',
            name='status',
            field=models.CharField(choices=[('DEFAULT', 'Default'), ('SUCCESS', 'Success')], default='DEFAULT', max_length=10),
        ),
        migrations.AddField(
            model_name='children',
            name='surname',
            field=models.TextField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='parent',
            name='mobile_number',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='parent',
            name='name',
            field=models.TextField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='parent',
            name='surname',
            field=models.TextField(blank=True, max_length=15, null=True),
        ),
    ]
