# Generated by Django 4.1.7 on 2024-05-15 08:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('highlighted', models.TextField()),
                ('status', models.CharField(choices=[('Родитель', 'Родитель'), ('Ребёнок', 'Ребёнок'), ('Другое', 'Другое')], max_length=10)),
                ('photo', models.ImageField(default='Helping-Project/MAIN/photo/default.jpg', upload_to='photo')),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
                ('surname', models.CharField(blank=True, max_length=20, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=1000000)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('INITIAL', 'Initial'), ('COMPLETED', 'Completed')], default='INITIAL', max_length=10)),
                ('children', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children_task', to='mysite.profile')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parents_task', to='mysite.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('children', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='childrens', to='mysite.profile')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parents', to='mysite.profile')),
                ('requests_to_childrens', models.ManyToManyField(related_name='relation_childrens', to='mysite.profile')),
                ('requests_to_parents', models.ManyToManyField(related_name='relation_parents', to='mysite.profile')),
            ],
        ),
    ]
