# Generated by Django 4.1.7 on 2024-05-15 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='highlighted',
            field=models.TextField(blank=True, null=True),
        ),
    ]
