# Generated by Django 4.1.7 on 2024-05-15 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_alter_profile_highlighted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='highlighted',
        ),
    ]
