# Generated by Django 5.0.6 on 2024-06-03 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0007_alter_article_like_list_alter_comment_like_list_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relationship',
            name='children',
        ),
        migrations.RemoveField(
            model_name='relationship',
            name='parent',
        ),
        migrations.AlterField(
            model_name='relationship',
            name='requests_to_childrens',
            field=models.ManyToManyField(related_name='request_to_relation_childrens', to='mysite.profile'),
        ),
        migrations.AlterField(
            model_name='relationship',
            name='requests_to_parents',
            field=models.ManyToManyField(related_name='request_to_relation_parents', to='mysite.profile'),
        ),
        migrations.AddField(
            model_name='relationship',
            name='children',
            field=models.ManyToManyField(related_name='relation_childrens', to='mysite.profile'),
        ),
        migrations.AddField(
            model_name='relationship',
            name='parent',
            field=models.ManyToManyField(related_name='relation_parents', to='mysite.profile'),
        ),
    ]
