# Generated by Django 5.0.6 on 2024-06-03 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0008_remove_relationship_children_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relationship',
            name='children',
            field=models.ManyToManyField(blank=True, related_name='relation_childrens', to='mysite.profile'),
        ),
        migrations.AlterField(
            model_name='relationship',
            name='parent',
            field=models.ManyToManyField(blank=True, related_name='relation_parents', to='mysite.profile'),
        ),
    ]
