# Generated by Django 5.0.6 on 2024-06-03 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0009_alter_relationship_children_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relationship',
            name='requests_to_childrens',
            field=models.ManyToManyField(blank=True, related_name='request_to_relation_childrens', to='mysite.profile'),
        ),
        migrations.AlterField(
            model_name='relationship',
            name='requests_to_parents',
            field=models.ManyToManyField(blank=True, related_name='request_to_relation_parents', to='mysite.profile'),
        ),
    ]
