# Generated by Django 5.0.6 on 2024-06-04 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0011_alter_relationship_requests_to_childrens_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Chat',
            new_name='Message',
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
                ('current_profiles', models.ManyToManyField(blank=True, related_name='current_rooms', to='mysite.profile')),
            ],
        ),
        migrations.AlterField(
            model_name='message',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='mysite.room'),
        ),
        migrations.DeleteModel(
            name='Topic',
        ),
    ]
