# Generated by Django 5.0.6 on 2024-06-04 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0012_rename_chat_message_room_alter_message_room_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='relationship',
            name='list_on_invite',
            field=models.ManyToManyField(related_name='list_on_invite', to='mysite.profile'),
        ),
    ]
