# Generated by Django 5.0.6 on 2024-06-04 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0013_relationship_list_on_invite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relationship',
            name='list_on_invite',
            field=models.ManyToManyField(blank=True, related_name='list_on_invite', to='mysite.profile'),
        ),
        migrations.AlterField(
            model_name='relationship',
            name='requests_to_childrens',
            field=models.ManyToManyField(blank=True, related_name='request_to_relation_childrens', to='mysite.profile'),
        ),
        migrations.AlterField(
            model_name='relationship',
            name='requests_to_parents',
            field=models.ManyToManyField(blank=True, related_name='request_to_relation_parents', to='mysite.profile'),
        ),
    ]
